[package]
name = "dgraph-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dgraph-common = { path = "../engine/dgraph-common" }
dgraph-storage = { path = "../engine/dgraph-storage" }
dgraph-query = { path = "../engine/dgraph-query" }
dgraph-raft = { path = "../engine/dgraph-raft" }
dgraph-schema = { path = "../engine/dgraph-schema" }

[dev-dependencies]
proptest = "1.5"
