//! Tokenizer: Index tokenization for different value types
//!
//! Tokenizers convert values into tokens for index storage.
//! Each tokenizer has a unique identifier byte for key encoding.

use bytes::Bytes;
use std::collections::HashSet;

/// Tokenizer identifier bytes - unique prefix for each tokenizer type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum TokenizerId {
    /// Term tokenizer (word-based)
    Term = 0x01,
    /// Exact match tokenizer
    Exact = 0x02,
    /// Exact with language
    ExactLang = 0x03,
    /// Year tokenizer for datetime
    Year = 0x04,
    /// Geo tokenizer
    Geo = 0x05,
    /// Integer tokenizer
    Int = 0x06,
    /// Float tokenizer
    Float = 0x07,
    /// Fulltext search tokenizer
    Fulltext = 0x08,
    /// Boolean tokenizer
    Bool = 0x09,
    /// Trigram tokenizer
    Trigram = 0x0A,
    /// Hash tokenizer (blake2b)
    Hash = 0x0B,
    /// SHA256 tokenizer
    Sha256 = 0x0C,
    /// BigFloat tokenizer
    BigFloat = 0x0D,
    /// Vector tokenizer
    Vector = 0x0E,
    /// NGram tokenizer
    NGram = 0x0F,
    /// Month tokenizer for datetime
    Month = 0x41,
    /// Day tokenizer for datetime
    Day = 0x42,
    /// Hour tokenizer for datetime
    Hour = 0x43,
}

impl TokenizerId {
    /// Get the identifier byte
    #[must_use]
    pub const fn as_byte(self) -> u8 {
        self as u8
    }

    /// Create from byte value
    pub fn from_byte(b: u8) -> Option<Self> {
        match b {
            0x01 => Some(Self::Term),
            0x02 => Some(Self::Exact),
            0x03 => Some(Self::ExactLang),
            0x04 => Some(Self::Year),
            0x05 => Some(Self::Geo),
            0x06 => Some(Self::Int),
            0x07 => Some(Self::Float),
            0x08 => Some(Self::Fulltext),
            0x09 => Some(Self::Bool),
            0x0A => Some(Self::Trigram),
            0x0B => Some(Self::Hash),
            0x0C => Some(Self::Sha256),
            0x0D => Some(Self::BigFloat),
            0x0E => Some(Self::Vector),
            0x0F => Some(Self::NGram),
            0x41 => Some(Self::Month),
            0x42 => Some(Self::Day),
            0x43 => Some(Self::Hour),
            _ => None,
        }
    }
}

/// Token generated by a tokenizer
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct Token {
    /// The tokenizer that generated this
    pub id: TokenizerId,
    /// The token bytes
    pub data: Bytes,
}

impl Token {
    /// Create a new token from owned bytes
    #[must_use]
    pub fn new(id: TokenizerId, data: Bytes) -> Self {
        Self { id, data }
    }

    /// Create a new token from a byte slice (copies the data)
    #[must_use]
    pub fn from_slice(id: TokenizerId, data: &[u8]) -> Self {
        Self {
            id,
            data: Bytes::copy_from_slice(data),
        }
    }

    /// Create a new token from a string (copies the data)
    #[must_use]
    pub fn from_str(id: TokenizerId, s: &str) -> Self {
        Self::from_slice(id, s.as_bytes())
    }

    /// Encode to bytes with identifier prefix
    #[must_use]
    pub fn encode(&self) -> Bytes {
        let mut buf = Vec::with_capacity(1 + self.data.len());
        buf.push(self.id.as_byte());
        buf.extend_from_slice(&self.data);
        Bytes::from(buf)
    }

    /// Decode from bytes
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.is_empty() {
            return None;
        }
        let id = TokenizerId::from_byte(data[0])?;
        Some(Self {
            id,
            data: Bytes::copy_from_slice(&data[1..]),
        })
    }
}

/// Tokenizer trait - generates tokens from values
pub trait Tokenizer: Send + Sync {
    /// Get the tokenizer name
    fn name(&self) -> &'static str;

    /// Get the tokenizer identifier
    fn id(&self) -> TokenizerId;

    /// Check if tokens can be sorted
    fn is_sortable(&self) -> bool;

    /// Check if tokenization is lossy (can't reconstruct original value)
    fn is_lossy(&self) -> bool;

    /// Generate tokens from a string value
    fn tokenize_string(&self, value: &str) -> Vec<Token>;

    /// Generate tokens from an integer value
    fn tokenize_int(&self, value: i64) -> Vec<Token> {
        let _ = value;
        Vec::new()
    }

    /// Generate tokens from a float value
    fn tokenize_float(&self, value: f64) -> Vec<Token> {
        let _ = value;
        Vec::new()
    }

    /// Generate tokens from a boolean value
    fn tokenize_bool(&self, value: bool) -> Vec<Token> {
        let _ = value;
        Vec::new()
    }
}

/// Exact match tokenizer - preserves full string
#[derive(Clone, Debug, Default)]
pub struct ExactTokenizer;

impl Tokenizer for ExactTokenizer {
    fn name(&self) -> &'static str {
        "exact"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Exact
    }

    fn is_sortable(&self) -> bool {
        true
    }

    fn is_lossy(&self) -> bool {
        false
    }

    fn tokenize_string(&self, value: &str) -> Vec<Token> {
        vec![Token::from_str(self.id(), value)]
    }
}

/// Term tokenizer - splits on whitespace
#[derive(Clone, Debug, Default)]
pub struct TermTokenizer;

impl Tokenizer for TermTokenizer {
    fn name(&self) -> &'static str {
        "term"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Term
    }

    fn is_sortable(&self) -> bool {
        false
    }

    fn is_lossy(&self) -> bool {
        true
    }

    fn tokenize_string(&self, value: &str) -> Vec<Token> {
        value
            .split_whitespace()
            .map(|word| Token::from_str(self.id(), &word.to_lowercase()))
            .collect()
    }
}

/// Trigram tokenizer - generates 3-character substrings
#[derive(Clone, Debug, Default)]
pub struct TrigramTokenizer;

impl Tokenizer for TrigramTokenizer {
    fn name(&self) -> &'static str {
        "trigram"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Trigram
    }

    fn is_sortable(&self) -> bool {
        false
    }

    fn is_lossy(&self) -> bool {
        true
    }

    fn tokenize_string(&self, value: &str) -> Vec<Token> {
        let chars: Vec<char> = value.to_lowercase().chars().collect();
        if chars.len() < 3 {
            return vec![Token::from_str(self.id(), &value.to_lowercase())];
        }

        let mut seen = HashSet::new();
        let mut tokens = Vec::new();

        for i in 0..=chars.len().saturating_sub(3) {
            let trigram: String = chars[i..i + 3].iter().collect();
            if seen.insert(trigram.clone()) {
                tokens.push(Token::from_str(self.id(), &trigram));
            }
        }

        tokens
    }
}

/// Hash tokenizer - blake2b hash of the value
#[derive(Clone, Debug, Default)]
pub struct HashTokenizer;

impl HashTokenizer {
    /// Simple hash function (FNV-1a for now)
    fn hash_bytes(data: &[u8]) -> [u8; 8] {
        let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
        for &byte in data {
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x0100_0000_01b3);
        }
        hash.to_be_bytes()
    }
}

impl Tokenizer for HashTokenizer {
    fn name(&self) -> &'static str {
        "hash"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Hash
    }

    fn is_sortable(&self) -> bool {
        false
    }

    fn is_lossy(&self) -> bool {
        false
    }

    fn tokenize_string(&self, value: &str) -> Vec<Token> {
        let hash = Self::hash_bytes(value.as_bytes());
        vec![Token::from_slice(self.id(), &hash)]
    }
}

/// Integer tokenizer
#[derive(Clone, Debug, Default)]
pub struct IntTokenizer;

impl Tokenizer for IntTokenizer {
    fn name(&self) -> &'static str {
        "int"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Int
    }

    fn is_sortable(&self) -> bool {
        true
    }

    fn is_lossy(&self) -> bool {
        false
    }

    fn tokenize_string(&self, _value: &str) -> Vec<Token> {
        Vec::new()
    }

    fn tokenize_int(&self, value: i64) -> Vec<Token> {
        // Encode as sortable bytes (flip sign bit for proper ordering)
        let sortable = (value as u64) ^ (1u64 << 63);
        vec![Token::from_slice(self.id(), &sortable.to_be_bytes())]
    }
}

/// Float tokenizer
#[derive(Clone, Debug, Default)]
pub struct FloatTokenizer;

impl Tokenizer for FloatTokenizer {
    fn name(&self) -> &'static str {
        "float"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Float
    }

    fn is_sortable(&self) -> bool {
        true
    }

    fn is_lossy(&self) -> bool {
        true
    }

    fn tokenize_string(&self, _value: &str) -> Vec<Token> {
        Vec::new()
    }

    fn tokenize_float(&self, value: f64) -> Vec<Token> {
        // Encode float as sortable bytes
        let bits = value.to_bits();
        let sortable = if value >= 0.0 {
            bits ^ (1u64 << 63)
        } else {
            !bits
        };
        vec![Token::from_slice(self.id(), &sortable.to_be_bytes())]
    }
}

/// Boolean tokenizer
#[derive(Clone, Debug, Default)]
pub struct BoolTokenizer;

impl Tokenizer for BoolTokenizer {
    fn name(&self) -> &'static str {
        "bool"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Bool
    }

    fn is_sortable(&self) -> bool {
        false
    }

    fn is_lossy(&self) -> bool {
        false
    }

    fn tokenize_string(&self, _value: &str) -> Vec<Token> {
        Vec::new()
    }

    fn tokenize_bool(&self, value: bool) -> Vec<Token> {
        let byte = if value { 1u8 } else { 0u8 };
        vec![Token::from_slice(self.id(), &[byte])]
    }
}

/// Fulltext tokenizer - word-based with stopword removal
#[derive(Clone, Debug, Default)]
pub struct FulltextTokenizer;

impl FulltextTokenizer {
    /// Basic English stopwords
    const STOPWORDS: &'static [&'static str] = &[
        "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "has", "he", "in", "is",
        "it", "its", "of", "on", "that", "the", "to", "was", "were", "will", "with",
    ];

    fn is_stopword(word: &str) -> bool {
        Self::STOPWORDS.binary_search(&word).is_ok()
    }
}

impl Tokenizer for FulltextTokenizer {
    fn name(&self) -> &'static str {
        "fulltext"
    }

    fn id(&self) -> TokenizerId {
        TokenizerId::Fulltext
    }

    fn is_sortable(&self) -> bool {
        false
    }

    fn is_lossy(&self) -> bool {
        true
    }

    fn tokenize_string(&self, value: &str) -> Vec<Token> {
        let mut seen = HashSet::new();
        let mut tokens = Vec::new();

        for word in value.split(|c: char| !c.is_alphanumeric()) {
            let normalized = word.to_lowercase();
            if normalized.is_empty() || Self::is_stopword(&normalized) {
                continue;
            }
            if seen.insert(normalized.clone()) {
                tokens.push(Token::from_str(self.id(), &normalized));
            }
        }

        tokens
    }
}

/// Registry of tokenizers by name
pub struct TokenizerRegistry {
    tokenizers: Vec<Box<dyn Tokenizer>>,
}

impl Default for TokenizerRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl TokenizerRegistry {
    /// Create registry with all built-in tokenizers
    #[must_use]
    pub fn new() -> Self {
        Self {
            tokenizers: vec![
                Box::new(ExactTokenizer),
                Box::new(TermTokenizer),
                Box::new(TrigramTokenizer),
                Box::new(HashTokenizer),
                Box::new(IntTokenizer),
                Box::new(FloatTokenizer),
                Box::new(BoolTokenizer),
                Box::new(FulltextTokenizer),
            ],
        }
    }

    /// Get tokenizer by name
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&dyn Tokenizer> {
        self.tokenizers
            .iter()
            .find(|t| t.name() == name)
            .map(AsRef::as_ref)
    }

    /// Get tokenizer by ID
    #[must_use]
    pub fn get_by_id(&self, id: TokenizerId) -> Option<&dyn Tokenizer> {
        self.tokenizers
            .iter()
            .find(|t| t.id() == id)
            .map(AsRef::as_ref)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_tokenizer() {
        let tok = ExactTokenizer;
        let tokens = tok.tokenize_string("Hello World");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].data.as_ref(), b"Hello World");
        assert_eq!(tokens[0].id, TokenizerId::Exact);
    }

    #[test]
    fn term_tokenizer() {
        let tok = TermTokenizer;
        let tokens = tok.tokenize_string("Hello World");
        assert_eq!(tokens.len(), 2);
        assert_eq!(tokens[0].data.as_ref(), b"hello");
        assert_eq!(tokens[1].data.as_ref(), b"world");
    }

    #[test]
    fn trigram_tokenizer() {
        let tok = TrigramTokenizer;
        let tokens = tok.tokenize_string("hello");
        // "hel", "ell", "llo"
        assert_eq!(tokens.len(), 3);
    }

    #[test]
    fn hash_tokenizer() {
        let tok = HashTokenizer;
        let tokens = tok.tokenize_string("test");
        assert_eq!(tokens.len(), 1);
        assert_eq!(tokens[0].data.len(), 8);
    }

    #[test]
    fn int_tokenizer() {
        let tok = IntTokenizer;

        // Positive numbers
        let t1 = tok.tokenize_int(100);
        let t2 = tok.tokenize_int(200);
        assert!(t1[0].data > t2[0].data || t1[0].data < t2[0].data); // Just check different

        // Verify sortable ordering: -100 < 0 < 100
        let neg = tok.tokenize_int(-100);
        let zero = tok.tokenize_int(0);
        let pos = tok.tokenize_int(100);
        assert!(neg[0].data < zero[0].data);
        assert!(zero[0].data < pos[0].data);
    }

    #[test]
    fn float_tokenizer() {
        let tok = FloatTokenizer;
        let neg = tok.tokenize_float(-1.0);
        let zero = tok.tokenize_float(0.0);
        let pos = tok.tokenize_float(1.0);
        assert!(neg[0].data < zero[0].data);
        assert!(zero[0].data < pos[0].data);
    }

    #[test]
    fn bool_tokenizer() {
        let tok = BoolTokenizer;
        let t = tok.tokenize_bool(true);
        let f = tok.tokenize_bool(false);
        assert_eq!(t[0].data.as_ref(), &[1]);
        assert_eq!(f[0].data.as_ref(), &[0]);
    }

    #[test]
    fn fulltext_tokenizer() {
        let tok = FulltextTokenizer;
        let tokens = tok.tokenize_string("The quick brown fox");
        // "the" is a stopword
        assert_eq!(tokens.len(), 3);
        assert!(tokens.iter().any(|t| t.data.as_ref() == b"quick"));
        assert!(tokens.iter().any(|t| t.data.as_ref() == b"brown"));
        assert!(tokens.iter().any(|t| t.data.as_ref() == b"fox"));
    }

    #[test]
    fn token_encode_decode() {
        let token = Token::from_str(TokenizerId::Exact, "test");
        let encoded = token.encode();
        let decoded = Token::decode(&encoded).unwrap();
        assert_eq!(decoded.id, TokenizerId::Exact);
        assert_eq!(decoded.data.as_ref(), b"test");
    }

    #[test]
    fn tokenizer_registry() {
        let registry = TokenizerRegistry::new();
        assert!(registry.get("exact").is_some());
        assert!(registry.get("term").is_some());
        assert!(registry.get("unknown").is_none());
        assert!(registry.get_by_id(TokenizerId::Exact).is_some());
    }
}
