[package]
name = "dgraph-raft"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dgraph-common.workspace = true
dgraph-storage.workspace = true
tokio.workspace = true
tracing.workspace = true
bytes.workspace = true
parking_lot.workspace = true
crossbeam.workspace = true
